credentials:
  usernames:
    sumitkant:
      email: sumitkant@iiml.org
      name: Sumit Kant
      password: $2b$12$GUAxiYTWuNqDEH2Zdg8q2eMiCrkdQ8oJOxSLYcHcxacpd8BLs78Zu
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - sumitkant@iiml.org
